Repository amberframework/docs, pull requests merged in 2018-06, with the labels that each got.

#82 docs/deployment/manual-deploy.md
  deployment/manual-deploy.md
Labels: kind:documentation, pr:needs-review

#83 manual-deploy.md
  deployment/README.md
Labels: kind:documentation, pr:needs-review

#84 Update new.md
  cli/new.md
Labels: kind:documentation, kind:enhancement, pr:needs-review

#86 Fixes a couple of typos
  guides/controllers/halt.md
Labels: kind:documentation, kind:enhancement

#89 Removes Amber Deploy From Docs
  cli/deploy.md
Labels: kind:documentation

#88 Removes Amber Deploy From Docs
  cli/README.md
Labels: kind:documentation

#92 Proof read overview
  guides/overview.md
Labels: kind:documentation, kind:enhancement

#91 Small improvements
  getting-started/quick-start.md
Labels: kind:documentation, kind:enhancement

#90 Update for Amber v0.8.0 release
  getting-started/README.md
Labels: kind:documentation, pr:needs-review

#95 Fixed response_with references
  cookbook/json-api.md
Labels: kind:documentation

#93 Proof Read Installation
  guides/installation.md
Labels: kind:documentation, pr:needs-review

#96 Removes Multi Params
  guides/controllers/request-and-response-objects.md
Labels: pr:needs-review

#94 Improves Params Validation Docs
  guides/controllers/params-validation.md
Labels: pr:needs-review
